create table if not exists public.intentlock_events (
  id bigint generated by default as identity primary key,
  session_id text not null check (char_length(session_id) between 8 and 64),
  event_name text not null check (event_name in ('visit', 'analysis_completed', 'repeat_use', 'result_copied', 'pricing_interest')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_intentlock_events_name_created
  on public.intentlock_events (event_name, created_at desc);

alter table public.intentlock_events enable row level security;
